.github/workflows: quote bash command

diff --git a/.github/workflows/appsec.yml b/.github/workflows/appsec.yml
--- a/.github/workflows/appsec.yml
+++ b/.github/workflows/appsec.yml
@@ -272,65 +272,59 @@ jobs:
         run: |
           sudo docker exec -i test.runner env CGO_ENABLED=0 go test -v $PACKAGES
           for submodule in $SUBMODULES; do
-            if ! sudo docker exec -i test.runner env CGO_ENABLED=0 cd $submodule && go test -v .; then
-              echo "Failed: env CGO_ENABLED=0 cd $submodule && go test -v . (submodule: $submodule)"
+            if ! sudo docker exec -i test.runner env CGO_ENABLED=0 bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=0 bash -c "cd $submodule && go test -v ." (submodule: $submodule)"
               exit 1
             fi
-            cd -
           done
       - name: NOCGO, appsec disabled
         run: |
           sudo docker exec -i test.runner env CGO_ENABLED=0 DD_APPSEC_ENABLED=false go test -v $PACKAGES
           for submodule in $SUBMODULES; do
-            if ! sudo docker exec -i test.runner env CGO_ENABLED=0 DD_APPSEC_ENABLED=false cd $submodule && go test -v .; then
-              echo "Failed: env CGO_ENABLED=0 DD_APPSEC_ENABLED=false cd $submodule && go test -v . (submodule: $submodule)"
+            if ! sudo docker exec -i test.runner env CGO_ENABLED=0 DD_APPSEC_ENABLED=false bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=0 DD_APPSEC_ENABLED=false bash -c "cd $submodule && go test -v ." (submodule: $submodule)"
               exit 1
             fi
-            cd -
           done
       - name: NOCGO, appsec enabled
         run: |
           sudo docker exec -i test.runner env CGO_ENABLED=0 DD_APPSEC_ENABLED=true go test -v $PACKAGES
           for submodule in $SUBMODULES; do
             cd $submodule
-            if ! sudo docker exec -i test.runner env CGO_ENABLED=0 DD_APPSEC_ENABLED=true cd $submodule && go test -v .; then
-              echo "Failed: env CGO_ENABLED=0 DD_APPSEC_ENABLED=true cd $submodule && go test -v . (submodule: $submodule)"
+            if ! sudo docker exec -i test.runner env CGO_ENABLED=0 DD_APPSEC_ENABLED=true bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=0 DD_APPSEC_ENABLED=true bash -c "cd $submodule && go test -v ." (submodule: $submodule)"
               exit 1
             fi
-            cd -
           done
       - name: CGO, undefined appsec state
         run: |
           sudo docker exec -i test.runner env CGO_ENABLED=1 go test -v $PACKAGES
           for submodule in $SUBMODULES; do
             cd $submodule
-            if ! sudo docker exec -i test.runner env CGO_ENABLED=1 cd $submodule && go test -v .; then
-              echo "Failed: env CGO_ENABLED=1 cd $submodule && go test -v . (submodule: $submodule)"
+            if ! sudo docker exec -i test.runner env CGO_ENABLED=1 bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=1 bash -c "cd $submodule && go test -v ." (submodule: $submodule)"
               exit 1
             fi
-            cd -
           done
       - name: CGO, appsec disabled
         run: |
           sudo docker exec -i test.runner env CGO_ENABLED=1 DD_APPSEC_ENABLED=false go test -v $PACKAGES
           for submodule in $SUBMODULES; do
             cd $submodule
-            if ! sudo docker exec -i test.runner env CGO_ENABLED=1 DD_APPSEC_ENABLED=false cd $submodule && go test -v .; then
-              echo "Failed: env CGO_ENABLED=1 DD_APPSEC_ENABLED=false cd $submodule && go test -v . (submodule: $submodule)"
+            if ! sudo docker exec -i test.runner env CGO_ENABLED=1 DD_APPSEC_ENABLED=false bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=1 DD_APPSEC_ENABLED=false bash -c "cd $submodule && go test -v ." (submodule: $submodule)"
               exit 1
             fi
-            cd -
           done
       - name: CGO, appsec enabled
         run: |
           sudo docker exec -i test.runner env CGO_ENABLED=1 DD_APPSEC_ENABLED=true go test -v $PACKAGES
           for submodule in $SUBMODULES; do
             cd $submodule
-            if ! sudo docker exec -i test.runner env CGO_ENABLED=1 DD_APPSEC_ENABLED=true cd $submodule && go test -v .; then
-              echo "Failed: env CGO_ENABLED=1 DD_APPSEC_ENABLED=true cd $submodule && go test -v . (submodule: $submodule)"
+            if ! sudo docker exec -i test.runner env CGO_ENABLED=1 DD_APPSEC_ENABLED=true bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=1 DD_APPSEC_ENABLED=true bash -c "cd $submodule && go test -v ." (submodule: $submodule)"
               exit 1
             fi
-            cd -
           done
 
       - name: Clean up
