.github/workflows: move envs to docker env args

diff --git a/.github/workflows/appsec.yml b/.github/workflows/appsec.yml
--- a/.github/workflows/appsec.yml
+++ b/.github/workflows/appsec.yml
@@ -270,55 +270,55 @@ jobs:
 
       - name: NOCGO, undefined appsec state
         run: |
-          sudo docker exec -i test.runner "env CGO_ENABLED=0 go test -v $PACKAGES"
+          sudo docker exec -i -e CGO_ENABLED=0 test.runner go test -v $PACKAGES
           for submodule in $SUBMODULES; do
-            if ! sudo docker exec -i test.runner "env CGO_ENABLED=0 bash -c \"cd $submodule && go test -v .\""; then
-              echo "Failed: env CGO_ENABLED=0 bash -c \"cd $submodule && go test -v .\" (submodule: $submodule)"
+            if ! sudo docker exec -i -e CGO_ENABLED=0 test.runner bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=0 bash -c "cd $submodule && go test -v .\" (submodule: $submodule)"
               exit 1
             fi
           done
       - name: NOCGO, appsec disabled
         run: |
-          sudo docker exec -i test.runner "env CGO_ENABLED=0 DD_APPSEC_ENABLED=false go test -v $PACKAGES"
+          sudo docker exec -i -e CGO_ENABLED=0 -e DD_APPSEC_ENABLED=false test.runner go test -v $PACKAGES
           for submodule in $SUBMODULES; do
-            if ! sudo docker exec -i test.runner "env CGO_ENABLED=0 DD_APPSEC_ENABLED=false bash -c \"cd $submodule && go test -v .\""; then
-              echo "Failed: env CGO_ENABLED=0 DD_APPSEC_ENABLED=false bash -c \"cd $submodule && go test -v .\" (submodule: $submodule)"
+            if ! sudo docker exec -i -e CGO_ENABLED=0 -e DD_APPSEC_ENABLED=false test.runner bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=0 DD_APPSEC_ENABLED=false bash -c "cd $submodule && go test -v .\" (submodule: $submodule)"
               exit 1
             fi
           done
       - name: NOCGO, appsec enabled
         run: |
-          sudo docker exec -i test.runner "env CGO_ENABLED=0 DD_APPSEC_ENABLED=true go test -v $PACKAGES"
+          sudo docker exec -i -e CGO_ENABLED=0 -e DD_APPSEC_ENABLED=true go test -v $PACKAGES
           for submodule in $SUBMODULES; do
-            if ! sudo docker exec -i test.runner "env CGO_ENABLED=0 DD_APPSEC_ENABLED=true bash -c \"cd $submodule && go test -v .\""; then
-              echo "Failed: env CGO_ENABLED=0 DD_APPSEC_ENABLED=true bash -c \"cd $submodule && go test -v .\" (submodule: $submodule)"
+            if ! sudo docker exec -i -e CGO_ENABLED=0 -e DD_APPSEC_ENABLED=true test.runner bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=0 DD_APPSEC_ENABLED=true bash -c "cd $submodule && go test -v .\" (submodule: $submodule)"
               exit 1
             fi
           done
       - name: CGO, undefined appsec state
         run: |
-          sudo docker exec -i test.runner "env CGO_ENABLED=1 go test -v $PACKAGES"
+          sudo docker exec -i -e CGO_ENABLED=1 test.runner go test -v $PACKAGES
           for submodule in $SUBMODULES; do
-            if ! sudo docker exec -i test.runner "env CGO_ENABLED=1 bash -c \"cd $submodule && go test -v .\""; then
-              echo "Failed: env CGO_ENABLED=1 bash -c \"cd $submodule && go test -v .\" (submodule: $submodule)"
+            if ! sudo docker exec -i -e CGO_ENABLED=1 test.runner bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=1 bash -c "cd $submodule && go test -v .\" (submodule: $submodule)"
               exit 1
             fi
           done
       - name: CGO, appsec disabled
         run: |
-          sudo docker exec -i test.runner "env CGO_ENABLED=1 DD_APPSEC_ENABLED=false go test -v $PACKAGES"
+          sudo docker exec -i -e CGO_ENABLED=1 -e DD_APPSEC_ENABLED=false test.runner go test -v $PACKAGES
           for submodule in $SUBMODULES; do
-            if ! sudo docker exec -i test.runner "env CGO_ENABLED=1 DD_APPSEC_ENABLED=false bash -c \"cd $submodule && go test -v .\""; then
-              echo "Failed: env CGO_ENABLED=1 DD_APPSEC_ENABLED=false bash -c \"cd $submodule && go test -v .\" (submodule: $submodule)"
+            if ! sudo docker exec -i -e CGO_ENABLED=1 -e DD_APPSEC_ENABLED=false test.runner bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=1 DD_APPSEC_ENABLED=false bash -c "cd $submodule && go test -v .\" (submodule: $submodule)"
               exit 1
             fi
           done
       - name: CGO, appsec enabled
         run: |
-          sudo docker exec -i test.runner "env CGO_ENABLED=1 DD_APPSEC_ENABLED=true go test -v $PACKAGES"
+          sudo docker exec -i -e CGO_ENABLED=1 -e DD_APPSEC_ENABLED=true test.runner go test -v $PACKAGES
           for submodule in $SUBMODULES; do
-            if ! sudo docker exec -i test.runner "env CGO_ENABLED=1 DD_APPSEC_ENABLED=true bash -c \"cd $submodule && go test -v .\""; then
-              echo "Failed: env CGO_ENABLED=1 DD_APPSEC_ENABLED=true bash -c \"cd $submodule && go test -v .\" (submodule: $submodule)"
+            if ! sudo docker exec -i -e CGO_ENABLED=1 -e DD_APPSEC_ENABLED=true test.runner bash -c "cd $submodule && go test -v ."; then
+              echo "Failed: env CGO_ENABLED=1 DD_APPSEC_ENABLED=true bash -c "cd $submodule && go test -v .\" (submodule: $submodule)"
               exit 1
             fi
           done
