feat(.github/workflows): swap pull-request and main-branch-tests, so flakiness is more probable while testing the PR

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -14,12 +14,39 @@ concurrency:
 jobs:
   unit-integration-tests:
     name: PR Unit and Integration Tests
+    strategy:
+      matrix:
+        go-version: [ "1.24", "1.25" ]
+      fail-fast: false
     uses: ./.github/workflows/unit-integration-tests.yml
-    permissions:
-      contents: read
-      id-token: write
-      pull-requests: write
     with:
-      go-version: "1.24"
-      ref: ${{ github.ref }}
+      go-version: ${{ matrix.go-version }}
+      ref: ${{ github.sha }}
     secrets: inherit
+  multios-unit-tests:
+    strategy:
+      matrix:
+        runs-on: [ macos-latest, windows-latest, ubuntu-latest ]
+        go-version: [ "1.24", "1.25" ]
+      fail-fast: false
+    uses: ./.github/workflows/multios-unit-tests.yml
+    with:
+      go-version: ${{ matrix.go-version }}
+      runs-on: ${{ matrix.runs-on }}
+      ref: ${{ github.sha }}
+    secrets: inherit
+  # This is a simple join point to make it easy to set up branch protection rules in GitHub.
+  pull-request-tests-done:
+    name: PR Unit and Integration Tests
+    needs:
+      - unit-integration-tests
+      - multios-unit-tests
+    runs-on: ubuntu-latest
+    if: success() || failure()
+    steps:
+      - name: Success
+        if: needs.unit-integration-tests.result == 'success' && needs.multios-unit-tests.result == 'success'
+        run: echo "Success!"
+      - name: Failure
+        if: needs.unit-integration-tests.result != 'success' || needs.multios-unit-tests.result != 'success'
+        run: echo "Failure!" && exit 1
