play around with smoke and system tests

diff --git a/.github/workflows/smoke-tests.yml b/.github/workflows/smoke-tests.yml
--- a/.github/workflows/smoke-tests.yml
+++ b/.github/workflows/smoke-tests.yml
@@ -15,6 +15,7 @@ on:
     branches:
       - main
       - release-v*
+      - hannahkm/require-system-smoke-tests
     tags-ignore:
       - 'contrib/**'
       - 'instrumentation/**'
@@ -196,3 +197,16 @@ jobs:
             go_libddwaf_ref=${{ inputs.go-libddwaf-ref }}
       - name: Test
         run: docker run -p7777:7777 --rm smoke-test
+
+  smoke-tests-done:
+    name: Smoke Tests
+    needs: smoke-tests
+    runs-on: ubuntu-latest
+    if: success() || failure()
+    steps:
+      - name: Success
+        if: needs.smoke-tests.result == 'success'
+        run: echo "Success!"
+      - name: Failure
+        if: needs.smoke-tests.result != 'success'
+        run: echo "Failure!" && exit 1
diff --git a/.github/workflows/system-tests.yml b/.github/workflows/system-tests.yml
--- a/.github/workflows/system-tests.yml
+++ b/.github/workflows/system-tests.yml
@@ -11,6 +11,7 @@ on:
     branches:
       - main
       - release-v*
+      - hannahkm/require-system-smoke-tests
     tags-ignore:
       - 'contrib/**'
       - 'instrumentation/**'
@@ -162,3 +163,16 @@ jobs:
         with:
           name: logs_${{ matrix.weblog-variant }}_${{ matrix.scenario }}
           path: artifact.tar.gz
+
+  system-tests-done:
+    name: System Tests
+    needs: system-tests
+    runs-on: ubuntu-latest
+    if: success() || failure()
+    steps:
+      - name: Success
+        if: needs.system-tests.result == 'success'
+        run: echo "Success!"
+      - name: Failure
+        if: needs.system-tests.result != 'success'
+        run: echo "Failure!" && exit 1
