update test agent image

diff --git a/.github/workflows/unit-integration-tests.yml b/.github/workflows/unit-integration-tests.yml
--- a/.github/workflows/unit-integration-tests.yml
+++ b/.github/workflows/unit-integration-tests.yml
@@ -62,13 +62,13 @@ jobs:
           - 8125:8125/udp
           - 8126:8126
       testagent:
-        image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:v1.10.1
+        image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:v1.11.0
         ports:
           - 9126:9126
         env:
           LOG_LEVEL: DEBUG
           TRACE_LANGUAGE: golang
-          DISABLED_CHECKS: trace_content_length,meta_tracer_version_header
+          ENABLED_CHECKS: trace_stall,trace_count_header,trace_peer_service,trace_dd_service
           PORT: 9126
           DD_SUPPRESS_TRACE_PARSE_ERRORS: true
           DD_POOL_TRACE_CHECK_FAILURES: true
@@ -206,6 +206,29 @@ jobs:
         if: always()
         shell: bash
         run: docker logs ${{ job.services.testagent.id }}
+
+      - name: Get Datadog APM Test Agent Trace Check Summary Results
+        if: always()
+        shell: bash
+        run: |
+              RESPONSE=$(curl -s -w "\n%{http_code}" -o response.txt "http://127.0.0.1:9126/test/trace_check/failures?return_all=true")
+              RESPONSE_CODE=$(echo "$RESPONSE" | awk 'END {print $NF}')
+              SUMMARY_RESPONSE=$(curl -s -w "\n%{http_code}" -o summary_response.txt "http://127.0.0.1:9126/test/trace_check/summary?return_all=true")
+              SUMMARY_RESPONSE_CODE=$(echo "$SUMMARY_RESPONSE" | awk 'END {print $NF}')
+              if [[ $RESPONSE_CODE -eq 200 ]]; then
+                  echo " "
+                  cat response.txt
+                  echo " - All APM Test Agent Check Traces returned successful!"
+                  echo "APM Test Agent Check Traces Summary Results:"
+                  cat summary_response.txt | jq "."
+              else
+                  echo "APM Test Agent Check Traces failed with response code: $RESPONSE_CODE"
+                  echo "Failures:"
+                  cat response.txt
+                  echo "APM Test Agent Check Traces Summary Results:"
+                  cat summary_response.txt | jq "."
+                  exit 1
+              fi
 
       - name: Testing outlier google.golang.org/api
         run: |
