add summary results

diff --git a/.github/workflows/unit-integration-tests.yml b/.github/workflows/unit-integration-tests.yml
--- a/.github/workflows/unit-integration-tests.yml
+++ b/.github/workflows/unit-integration-tests.yml
@@ -260,6 +260,30 @@ jobs:
         shell: bash
         run: docker logs ${{ job.services.testagent.id }}
 
+      - name: Get Datadog APM Test Agent Trace Check Summary Results
+        if: always()
+        shell: bash
+        run: |    
+              RESPONSE=$(curl -s -w "\n%{http_code}" -o response.txt http://127.0.0.1:9126/test/trace_check/failures)
+              RESPONSE_CODE=$(echo "$RESPONSE" | awk 'END {print $NF}')
+
+              SUMMARY_RESPONSE=$(curl -s -w "\n%{http_code}" -o summary_response.txt http://127.0.0.1:9126/test/trace_check/summary)
+              SUMMARY_RESPONSE_CODE=$(echo "$SUMMARY_RESPONSE" | awk 'END {print $NF}')
+              
+              if [[ $RESPONSE_CODE -eq 200 ]]; then
+                echo "All APM Test Agent Check Traces returned successful! (HTTP 200)"
+                cat response.txt
+                echo "APM Test Agent Check Traces Summary Results:"
+                cat summary_response.txt | jq '.'
+              else
+                echo "APM Test Agent Check Traces failed with response code: $RESPONSE_CODE"
+                echo "Failures:"
+                cat response.txt
+                echo "APM Test Agent Check Traces Summary Results:"
+                cat summary_response.txt | jq '.'
+                exit 1
+              fi
+
       - name: Testing outlier google.golang.org/api
         run: |
               go get google.golang.org/api@v0.121.0 # version used to generate code
