add test agent failure summary

diff --git a/.github/workflows/unit-integration-tests.yml b/.github/workflows/unit-integration-tests.yml
--- a/.github/workflows/unit-integration-tests.yml
+++ b/.github/workflows/unit-integration-tests.yml
@@ -264,24 +264,25 @@ jobs:
         if: always()
         shell: bash
         run: |    
-              RESPONSE=$(curl -s -w "\n%{http_code}" -o response.txt http://127.0.0.1:9126/test/trace_check/failures)
+              RESPONSE=$(curl -s -w "\n%{http_code}" -o response.txt http://127.0.0.1:9126/test/trace_check/failures?return_all=true)
               RESPONSE_CODE=$(echo "$RESPONSE" | awk 'END {print $NF}')
 
-              SUMMARY_RESPONSE=$(curl -s -w "\n%{http_code}" -o summary_response.txt http://127.0.0.1:9126/test/trace_check/summary)
+              SUMMARY_RESPONSE=$(curl -s -w "\n%{http_code}" -o summary_response.txt http://127.0.0.1:9126/test/trace_check/summary?return_all=true)
               SUMMARY_RESPONSE_CODE=$(echo "$SUMMARY_RESPONSE" | awk 'END {print $NF}')
-              
+
               if [[ $RESPONSE_CODE -eq 200 ]]; then
-                echo "All APM Test Agent Check Traces returned successful! (HTTP 200)"
-                cat response.txt
-                echo "APM Test Agent Check Traces Summary Results:"
-                cat summary_response.txt | jq '.'
+                  echo " "
+                  cat response.txt
+                  echo " - All APM Test Agent Check Traces returned successful!"
+                  echo "APM Test Agent Check Traces Summary Results:"
+                  cat summary_response.txt | jq '.'
               else
-                echo "APM Test Agent Check Traces failed with response code: $RESPONSE_CODE"
-                echo "Failures:"
-                cat response.txt
-                echo "APM Test Agent Check Traces Summary Results:"
-                cat summary_response.txt | jq '.'
-                exit 1
+                  echo "APM Test Agent Check Traces failed with response code: $RESPONSE_CODE"
+                  echo "Failures:"
+                  cat response.txt
+                  echo "APM Test Agent Check Traces Summary Results:"
+                  cat summary_response.txt | jq '.'
+                  exit 1
               fi
 
       - name: Testing outlier google.golang.org/api
