[ci] improve testing times for contrib tests (#3493)

diff --git a/.github/workflows/unit-integration-tests.yml b/.github/workflows/unit-integration-tests.yml
--- a/.github/workflows/unit-integration-tests.yml
+++ b/.github/workflows/unit-integration-tests.yml
@@ -105,12 +105,32 @@ jobs:
           reporter: github-pr-review
           workdir: internal/orchestrion/_integration
 
-  test-contrib:
+  set-up:
+    runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.matrix.outputs.matrix }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
+        with:
+          ref: ${{ inputs.ref || github.ref }}
+          
+      - name: Compute Matrix
+        id: matrix
+        run: |-
+          echo -n "matrix="                      >> "${GITHUB_OUTPUT}"
+          go run ./internal/contrib/matrix       >> "${GITHUB_OUTPUT}"
+
+  test-contrib-matrix:
+    needs: set-up
     runs-on:
       group: "APM Larger Runners"
     env:
-       TEST_RESULTS: /tmp/test-results # path to where test results will be saved
-       INTEGRATION: true
+        TEST_RESULTS: /tmp/test-results # path to where test results will be saved
+        INTEGRATION: true
+    strategy:
+      matrix:
+        chunk: ${{ fromJson(needs.set-up.outputs.matrix) }}
     services:
       datadog-agent:
         image: datadog/agent:latest
@@ -170,8 +190,8 @@ jobs:
       mssql:
         image: mcr.microsoft.com/mssql/server:2019-latest
         env:
-         SA_PASSWORD: myPassw0rd
-         ACCEPT_EULA: Y
+          SA_PASSWORD: myPassw0rd
+          ACCEPT_EULA: Y
         ports:
           - 1433:1433
       consul:
@@ -266,56 +286,23 @@ jobs:
 
       - name: Test Contrib
         if: always()
-        run: ./.github/workflows/apps/test-contrib-submodules.sh
-
-      - name: Upload the results to Datadog CI App
-        if: always()
-        continue-on-error: true
-        uses: ./.github/actions/dd-ci-upload
-        with:
-          dd-api-key: ${{ secrets.DD_CI_API_KEY }}
-          files: ${{ env.TEST_RESULTS }}/gotestsum-report*.xml
-          tags: go:${{ inputs.go-version }},arch:${{ runner.arch }},os:${{ runner.os }},distribution:${{ runner.distribution }}
-
-      - name: Upload Coverage
-        if: always()
-        continue-on-error: true
-        shell: bash
-        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
-
-      - name: Get Datadog APM Test Agent Logs
-        if: always()
-        shell: bash
-        run: docker logs ${{ job.services.testagent.id }}
-
-      - name: Get Datadog APM Test Agent Trace Check Summary Results
-        if: always()
-        shell: bash
         run: |
-              RESPONSE=$(curl -s -w "\n%{http_code}" -o response.txt "http://127.0.0.1:9126/test/trace_check/failures?return_all=true")
-              RESPONSE_CODE=$(echo "$RESPONSE" | awk 'END {print $NF}')
-              SUMMARY_RESPONSE=$(curl -s -w "\n%{http_code}" -o summary_response.txt "http://127.0.0.1:9126/test/trace_check/summary?return_all=true")
-              SUMMARY_RESPONSE_CODE=$(echo "$SUMMARY_RESPONSE" | awk 'END {print $NF}')
-              if [[ $RESPONSE_CODE -eq 200 ]]; then
-                  echo " "
-                  cat response.txt
-                  echo " - All APM Test Agent Check Traces returned successful!"
-                  echo "APM Test Agent Check Traces Summary Results:"
-                  cat summary_response.txt | jq "."
-              else
-                  echo "APM Test Agent Check Traces failed with response code: $RESPONSE_CODE"
-                  echo "Failures:"
-                  cat response.txt
-                  echo "APM Test Agent Check Traces Summary Results:"
-                  cat summary_response.txt | jq "."
-                  exit 1
-              fi
+          ./.github/workflows/apps/test-contrib-submodules.sh default ${{ toJson(matrix.chunk) }}
 
-      - name: Testing outlier google.golang.org/api
-        run: |
-              go get google.golang.org/api@v0.192.0 # version used to generate code
-              go mod tidy # Go1.16 doesn't update the sum file correctly after the go get, this tidy fixes it
-              go test -v ./...
+  test-contrib:
+    needs:
+      - test-contrib-matrix
+    runs-on:
+      group: "APM Larger Runners"
+    if: success() || failure()
+    continue-on-error: true
+    steps:
+      - name: Success
+        if: needs.test-contrib-matrix.result == 'success'
+        run: echo "Success!"
+      - name: Failure
+        if: needs.test-contrib-matrix.result != 'success'
+        run: echo "Failure!" && exit 1
 
   test-core:
     runs-on:
@@ -360,15 +347,81 @@ jobs:
             cd ./internal/exectracetest
             gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report-exectrace.xml -- -v -race -coverprofile=coverage.txt -covermode=atomic
 
+  upload-test-results:
+    needs:
+      - test-contrib
+      - test-core
+    runs-on:
+      group: "APM Larger Runners"
+    env:
+        TEST_RESULTS: /tmp/test-results # path to where test results will be saved
+    services:
+      datadog-agent:
+        image: datadog/agent:latest
+        env:
+          DD_HOSTNAME: "github-actions-worker"
+          DD_APM_ENABLED: true
+          DD_BIND_HOST: "0.0.0.0"
+          DD_API_KEY: "invalid_key_but_this_is_fine"
+          DD_TEST_AGENT_HOST: "localhost"
+          DD_TEST_AGENT_PORT: 9126
+        options: >-
+          --health-cmd "bash -c '</dev/tcp/127.0.0.1/8126'"
+        ports:
+          - 8125:8125/udp
+          - 8126:8126
+      testagent:
+        image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:v1.11.0
+        ports:
+          - 9126:9126
+        env:
+          LOG_LEVEL: DEBUG
+          TRACE_LANGUAGE: golang
+          ENABLED_CHECKS: trace_stall,trace_count_header,trace_peer_service,trace_dd_service
+          PORT: 9126
+          DD_SUPPRESS_TRACE_PARSE_ERRORS: true
+          DD_POOL_TRACE_CHECK_FAILURES: true
+          DD_DISABLE_ERROR_RESPONSES: true
+    steps:
       - name: Upload the results to Datadog CI App
         if: always()
         continue-on-error: true
         uses: ./.github/actions/dd-ci-upload
         with:
           dd-api-key: ${{ secrets.DD_CI_API_KEY }}
-          files: ${{ env.TEST_RESULTS }}/gotestsum-report.xml ${{ env.TEST_RESULTS }}/gotestsum-report-exectrace.xml
-          tags: go:${{ inputs.go-version }}},arch:${{ runner.arch }},os:${{ runner.os }},distribution:${{ runner.distribution }}
+          files: ${{ env.TEST_RESULTS }}/gotestsum-report*.xml
+          tags: go:${{ inputs.go-version }},arch:${{ runner.arch }},os:${{ runner.os }},distribution:${{ runner.distribution }}
+
       - name: Upload Coverage
         if: always()
+        continue-on-error: true
         shell: bash
         run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Get Datadog APM Test Agent Logs
+        if: always()
+        shell: bash
+        run: docker logs ${{ job.services.testagent.id }}
+
+      - name: Get Datadog APM Test Agent Trace Check Summary Results
+        if: always()
+        shell: bash
+        run: |
+              RESPONSE=$(curl -s -w "\n%{http_code}" -o response.txt "http://127.0.0.1:9126/test/trace_check/failures?return_all=true")
+              RESPONSE_CODE=$(echo "$RESPONSE" | awk 'END {print $NF}')
+              SUMMARY_RESPONSE=$(curl -s -w "\n%{http_code}" -o summary_response.txt "http://127.0.0.1:9126/test/trace_check/summary?return_all=true")
+              SUMMARY_RESPONSE_CODE=$(echo "$SUMMARY_RESPONSE" | awk 'END {print $NF}')
+              if [[ $RESPONSE_CODE -eq 200 ]]; then
+                  echo " "
+                  cat response.txt
+                  echo " - All APM Test Agent Check Traces returned successful!"
+                  echo "APM Test Agent Check Traces Summary Results:"
+                  cat summary_response.txt | jq "."
+              else
+                  echo "APM Test Agent Check Traces failed with response code: $RESPONSE_CODE"
+                  echo "Failures:"
+                  cat response.txt
+                  echo "APM Test Agent Check Traces Summary Results:"
+                  cat summary_response.txt | jq "."
+                  exit 1
+              fi
